# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import system_pb2 as system__pb2

GRPC_GENERATED_VERSION = '1.84.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in system_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ClientServiceStub:
    """1. Client Functions
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.login = channel.unary_unary(
                '/inventory.ClientService/login',
                request_serializer=system__pb2.LoginRequest.SerializeToString,
                response_deserializer=system__pb2.LoginResponse.FromString,
                _registered_method=True)
        self.logout = channel.unary_unary(
                '/inventory.ClientService/logout',
                request_serializer=system__pb2.TokenMessage.SerializeToString,
                response_deserializer=system__pb2.StatusMessage.FromString,
                _registered_method=True)
        self.post = channel.unary_unary(
                '/inventory.ClientService/post',
                request_serializer=system__pb2.PostRequest.SerializeToString,
                response_deserializer=system__pb2.StatusMessage.FromString,
                _registered_method=True)
        self.get = channel.unary_unary(
                '/inventory.ClientService/get',
                request_serializer=system__pb2.GetRequest.SerializeToString,
                response_deserializer=system__pb2.GetResponse.FromString,
                _registered_method=True)


class ClientServiceServicer:
    """1. Client Functions
    """

    def login(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def logout(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def post(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def get(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ClientServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'login': grpc.unary_unary_rpc_method_handler(
                    servicer.login,
                    request_deserializer=system__pb2.LoginRequest.FromString,
                    response_serializer=system__pb2.LoginResponse.SerializeToString,
            ),
            'logout': grpc.unary_unary_rpc_method_handler(
                    servicer.logout,
                    request_deserializer=system__pb2.TokenMessage.FromString,
                    response_serializer=system__pb2.StatusMessage.SerializeToString,
            ),
            'post': grpc.unary_unary_rpc_method_handler(
                    servicer.post,
                    request_deserializer=system__pb2.PostRequest.FromString,
                    response_serializer=system__pb2.StatusMessage.SerializeToString,
            ),
            'get': grpc.unary_unary_rpc_method_handler(
                    servicer.get,
                    request_deserializer=system__pb2.GetRequest.FromString,
                    response_serializer=system__pb2.GetResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'inventory.ClientService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('inventory.ClientService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ClientService:
    """1. Client Functions
    """

    @staticmethod
    def login(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/inventory.ClientService/login',
            system__pb2.LoginRequest.SerializeToString,
            system__pb2.LoginResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def logout(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/inventory.ClientService/logout',
            system__pb2.TokenMessage.SerializeToString,
            system__pb2.StatusMessage.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def post(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/inventory.ClientService/post',
            system__pb2.PostRequest.SerializeToString,
            system__pb2.StatusMessage.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def get(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/inventory.ClientService/get',
            system__pb2.GetRequest.SerializeToString,
            system__pb2.GetResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class AppServerServiceStub:
    """2. Application Server Functions (Inter-node communication for routing)
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.processBusinessRequest = channel.unary_unary(
                '/inventory.AppServerService/processBusinessRequest',
                request_serializer=system__pb2.BusinessRequest.SerializeToString,
                response_deserializer=system__pb2.StatusMessage.FromString,
                _registered_method=True)


class AppServerServiceServicer:
    """2. Application Server Functions (Inter-node communication for routing)
    """

    def processBusinessRequest(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AppServerServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'processBusinessRequest': grpc.unary_unary_rpc_method_handler(
                    servicer.processBusinessRequest,
                    request_deserializer=system__pb2.BusinessRequest.FromString,
                    response_serializer=system__pb2.StatusMessage.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'inventory.AppServerService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('inventory.AppServerService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class AppServerService:
    """2. Application Server Functions (Inter-node communication for routing)
    """

    @staticmethod
    def processBusinessRequest(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/inventory.AppServerService/processBusinessRequest',
            system__pb2.BusinessRequest.SerializeToString,
            system__pb2.StatusMessage.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class LLMServiceStub:
    """3. LLM Server Functions
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.getLLMAnswer = channel.unary_unary(
                '/inventory.LLMService/getLLMAnswer',
                request_serializer=system__pb2.LLMQuery.SerializeToString,
                response_deserializer=system__pb2.LLMAnswerResponse.FromString,
                _registered_method=True)


class LLMServiceServicer:
    """3. LLM Server Functions
    """

    def getLLMAnswer(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_LLMServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'getLLMAnswer': grpc.unary_unary_rpc_method_handler(
                    servicer.getLLMAnswer,
                    request_deserializer=system__pb2.LLMQuery.FromString,
                    response_serializer=system__pb2.LLMAnswerResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'inventory.LLMService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('inventory.LLMService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class LLMService:
    """3. LLM Server Functions
    """

    @staticmethod
    def getLLMAnswer(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/inventory.LLMService/getLLMAnswer',
            system__pb2.LLMQuery.SerializeToString,
            system__pb2.LLMAnswerResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class RaftServiceStub:
    """4. Raft Consensus Functions (Milestone 2)
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.requestVote = channel.unary_unary(
                '/inventory.RaftService/requestVote',
                request_serializer=system__pb2.VoteRequest.SerializeToString,
                response_deserializer=system__pb2.VoteReply.FromString,
                _registered_method=True)
        self.appendEntries = channel.unary_unary(
                '/inventory.RaftService/appendEntries',
                request_serializer=system__pb2.AppendEntriesRequest.SerializeToString,
                response_deserializer=system__pb2.AppendEntriesReply.FromString,
                _registered_method=True)


class RaftServiceServicer:
    """4. Raft Consensus Functions (Milestone 2)
    """

    def requestVote(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def appendEntries(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_RaftServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'requestVote': grpc.unary_unary_rpc_method_handler(
                    servicer.requestVote,
                    request_deserializer=system__pb2.VoteRequest.FromString,
                    response_serializer=system__pb2.VoteReply.SerializeToString,
            ),
            'appendEntries': grpc.unary_unary_rpc_method_handler(
                    servicer.appendEntries,
                    request_deserializer=system__pb2.AppendEntriesRequest.FromString,
                    response_serializer=system__pb2.AppendEntriesReply.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'inventory.RaftService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('inventory.RaftService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class RaftService:
    """4. Raft Consensus Functions (Milestone 2)
    """

    @staticmethod
    def requestVote(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/inventory.RaftService/requestVote',
            system__pb2.VoteRequest.SerializeToString,
            system__pb2.VoteReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def appendEntries(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/inventory.RaftService/appendEntries',
            system__pb2.AppendEntriesRequest.SerializeToString,
            system__pb2.AppendEntriesReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
